version: ~> 1.0
language: node_js
os:
 - linux
import:
 - ljharb/travis-ci:node/all.yml
 - ljharb/travis-ci:node/pretest.yml
 - ljharb/travis-ci:node/posttest.yml
 - ljharb/travis-ci:node/coverage.yml
matrix:
  allow_failures:
    - env: COVERAGE=true
